#!/bin/bash -eux
#
# Entrypoint for rpmbuild official Docker image
#

teardown() {
    # Ease debugging from Docker container by waiting for explicit shutdown.
    if [ -z "${CI-}" ] && ! test -t 0 ; then
        tail -f /dev/null
    fi
}

trap teardown EXIT INT TERM

: ${PGVERSION=10}
defines=(
	"--define=pgversion ${PGVERSION/./}"
	"--define=pginstdir /usr/pgsql-${PGVERSION}"
)

cd "$(readlink -m $0/..)"
sudo yum install -y gcc
sudo yum install -y $(rpmspec -q --buildrequires "${defines[@]}" pg_dumpacl.spec)
rpmbuild \
    --define "_sourcedir ${PWD}" \
    --define "_rpmdir ${PWD}/rpms" \
	"${defines[@]}" \
	-ba pg_dumpacl.spec
