version: "2"

workflows:
  version: 2
  pipeline:
    jobs:
    - 0-test
    - 0-rpm-centos7

jobs:
  0-test:
    working_directory: /workspace
    docker:
    - image: dalibo/postgres-sdk@sha256:b4b6b953235442cf6214ea6970934a572bb61f5b5525e9d28c651d54062b90cf
    - image: postgres:10-alpine
      environment:
        POSTGRES_HOST_AUTH_METHOD: trust
    steps:
    - checkout
    - run:
        name: Build pg_dumpacl
        environment:
          PG_CONFIG: /usr/lib/postgresql/10/bin/pg_config
          PGHOST: localhost
          PGUSER: postgres
        command: |
          make clean all
          wait-for-it.sh localhost:5432 -t 10
          sleep 1
          # Wait for restart
          wait-for-it.sh localhost:5432 -t 10
          ./fixture.sh
          ./pg_dumpacl -d db0
          ./pg_dumpacl --all
          export PGDATABASE=db0
          ./pg_dumpacl

  0-rpm-centos7:
    working_directory: /tmp/cci
    docker:
    - image: dalibo/labs-sdk:centos7
    steps:
    - checkout
    - run: ./pkg
    - store_artifacts: {path: /tmp/cci/rpms/x86_64}
